### ISSUE TITLE
TypeError after upgrading to 1.1.0

### ISSUE THREAD

**Issue by dlackty** [Shopify/memcached_store#34]
I thought it's related to the removal of Memcached::Rails. Will it be fixed by flushing the memcached server?

```
gems/memcached-1.8.0/lib/memcached/memcached.rb:728:in `memcached_cas': no implicit conversion of ActiveSupport::Cache::Entry into String (TypeError)
    from gems/memcached-1.8.0/lib/memcached/memcached.rb:728:in `single_cas'
    from gems/memcached-1.8.0/lib/memcached/memcached.rb:451:in `cas'
    from gems/memcached-1.8.0/lib/memcached/rails.rb:90:in `cas'
    from gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:80:in `block (2 levels) in cas'
    from gems/activesupport-5.0.2/lib/active_support/cache.rb:562:in `block in instrument'
    from gems/activesupport-5.0.2/lib/active_support/notifications.rb:166:in `instrument'
    from gems/activesupport-5.0.2/lib/active_support/cache.rb:562:in `instrument'
    from gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:79:in `block in cas'
    from gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:248:in `handle_exceptions'
    from gems/memcached_store-1.1.0/lib/active_support/cache/memcached_store.rb:78:in `cas'
    from gems/identity_cache-0.5.1/lib/identity_cache/cache_fetcher.rb:30:in `fetch'
    from gems/identity_cache-0.5.1/lib/identity_cache/memoized_cache_proxy.rb:57:in `fetch'
    from gems/identity_cache-0.5.1/lib/identity_cache.rb:115:in `fetch'
    from gems/identity_cache-0.5.1/lib/identity_cache/configuration_dsl.rb:259:in `attribute_dynamic_fetcher'
    from gems/identity_cache-0.5.1/lib/identity_cache/configuration_dsl.rb:199:in `fetch_id_by_token'
    from gems/identity_cache-0.5.1/lib/identity_cache/configuration_dsl.rb:54:in `fetch_by_token'
```

**Comment by rafaelfranca** [comment]
cc @alexsnaps

**Comment by rafaelfranca** [comment]
@dlackty are you passing a Memcached::Rails instance to the initializer of the cache store?

**Comment by alexsnaps** [comment]
Looks like this might indeed be the case... I'm thinking a guard about it in the `initialize` in order to fail early maybe appropriate in any case.

**Comment by dlackty** [comment]
@rafaelfranca Yes, exactly. Actually I copied the code from identity_cache's README and the current master still suggests using Memcached::Rails.

**Comment by alexsnaps** [comment]
I have updated the `README.md` in _this_ repo... but identity_cache also still references this indeed... 
https://github.com/shopify/identity_cache#installation 

That being said the gemspec also says: `'memcached_store', '~> 1.0.0'` (but as a dev dependency, not runtime). Anyways... Should we upgrade identity_cache? Just the docs? add a caveat?

**Comment by rafaelfranca** [comment]
Let's update identity_cache docs. For what I could get `memcached_store` is an optional dependency, if not we should change the gemspec. @dylanahsmith is that correct?

**Comment by dylanahsmith** [comment]
As far as I know, memcached_store is the only store that provides CAS support which is needed to avoid race conditions.  It will warn for any other cache adapters (except for ActiveSupport::Cache::MemoryStore and ActiveSupport::Cache::NullStore since they are useful for testing).

Why did we make a breaking change in a minor release of memcached_store?

**Comment by alexsnaps** [comment]
>Why did we make a breaking change in a minor release of memcached_store?

The breakage is somewhat unintentional... and is only being discovered now because nothing else used it in such a way. Most importantly no tests... i.e. the change was meant to only enable a new feature without breaking backwards compatibility, which got broken for a given setup now (i.e. injecting a `Memcached::Rails` instance to back the `MemcachedStore` instance; funnily enough that's the doc'ed setup).
